import { NextResponse } from "next/server";
import { pool } from "@/lib/db";

// SQL‑запросы для создания таблиц
const createTablesQuery = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email TEXT,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS consent_ppd (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    values TEXT,
    purpose TEXT,
    ip_address INET NOT NULL,          -- Обязательно
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_until TIMESTAMPTZ
  );

  CREATE TABLE IF NOT EXISTS consent_cookies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    consent_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cookie_categories JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    revoked_at TIMESTAMPTZ,
    ip_address INET NOT NULL,          -- Обязательно
    user_agent TEXT NOT NULL,         -- Обязательно
    page_url TEXT NOT NULL,           -- Обязательно
    consent_method VARCHAR(20) NOT NULL, -- Обязательно
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS food_intakes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TIME NOT NULL DEFAULT CURRENT_TIME,
    description TEXT NOT NULL,
    portion_size VARCHAR(20),
    carbs INTEGER,
    bread_units INTEGER,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS insulin_injections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TIME NOT NULL DEFAULT CURRENT_TIME,
    amount INTEGER NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS glucose_measurements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TIME NOT NULL DEFAULT CURRENT_TIME,
    amount REAL NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
`;

export async function GET() {
  try {
    await pool.query("BEGIN");
    await pool.query(createTablesQuery);
    await pool.query("COMMIT");

    return NextResponse.json(
      {
        success: true,
        message: "Таблицы созданы, данные внесены",
      },
      { status: 200 },
    );
  } catch (error) {
    // Откатываем транзакцию в случае ошибки
    await pool.query("ROLLBACK");
    console.error("Ошибка при создании таблиц:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Ошибка при создании таблиц и индексов",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}